[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fuel-prices"
  to = "/.netlify/functions/fuel-prices"
  status = 200

[functions]
  [functions.fuel-prices]
    schedule = "0 */6 * * *"
